services:
  drinkwater:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ~/Android/Sdk:/root/Android/Sdk
    ports:
      - "5173:5173"
    environment:
      - ANDROID_HOME=/root/Android/Sdk
      - PATH=/root/Android/Sdk/tools:/root/Android/Sdk/tools/bin:/root/Android/Sdk/platform-tools:$PATH
    command: ["yarn", "android:build"]
