platform :android do
  desc "Build APK para desenvolvimento"
  lane :build_apk do
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
  end

  desc "Build AAB para produção"
  lane :build_aab do
    gradle(
      task: "bundleRelease",
      print_command: true
    )
  end
end
