name: CI/CD Pipeline for React Native App

on:
  push:
    branches:
      - actions-test
  pull_request:
    branches:
      - actions-test

jobs:
  install-dependencies:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        run: yarn install

  build-android:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'openjdk'
          java-version: '17'

      - name: Build Docker image
        run: docker build -t drinkwater-android-builder .

      - name: Build Android APK
        run: |
          mkdir -p android/app/build/outputs/apk/release
          docker run --rm \
            -v ${{ github.workspace }}/android/app/build/outputs/apk/release:/app/android/app/build/outputs/apk/release \
            drinkwater-android-builder

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk

  # build-ios:
  #   runs-on: self-hosted
  #   needs: install-dependencies
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v2

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '18'

  #     - name: Check iOS environment
  #       run: |
  #         echo "Checking iOS environment..."
  #         xcodebuild -version
  #         pod --version

  #     - name: Install dependencies
  #       run: yarn install

  #     - name: Set up CocoaPods
  #       run: |
  #         cd ios
  #         pod install

  #     - name: Build iOS app
  #       run: |
  #         cd ios
  #         xcodebuild -workspace DrinkWater.xcworkspace -scheme DrinkWater -sdk iphoneos -configuration Release archive -archivePath $PWD/build/DrinkWater.xcarchive

  #     - name: Export IPA
  #       run: |
  #         xcodebuild -exportArchive -archivePath $PWD/build/DrinkWater.xcarchive -exportOptionsPlist ios/ExportOptions.plist -exportPath $PWD/build

  #     - name: Upload IPA to Artifacts
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: app-release.ipa
  #         path: ios/build/DrinkWater.ipa
