name: CI/CD Pipeline for React Native App

on:
  push:
    branches:
      - actions-test
  pull_request:
    branches:
      - actions-test

jobs:
  build-android-docker:
    runs-on: [self-hosted, docker-builder]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: drinkwater-android-builder:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Build Android APK
        run: |
          mkdir -p android/app/build/outputs/apk/release
          docker build -t drinkwater-android-builder:latest -f Dockerfile .
          docker run --rm drinkwater-android-builder:latest

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  build-android-native:
    runs-on: [self-hosted, android-builder]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Android APK
        run: |
          echo "Building Android APK..."
          rm -rf node_modules android ios .expo
          yarn install
          yarn android:build

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-release-native.apk
          path: android/app/build/outputs/apk/release/app-release.apk